/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.conexion;
import  java.sql.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;



/**
 *
 * @author baironMartin
 */
public class Administrador extends javax.swing.JFrame {
    String user,nombre_usuario;
    public static int secion_usuario;

    /**
     * Creates new form Adminnistrador
     */
    public Administrador() {
        initComponents();
        user= Login.user;
        secion_usuario=1;
        
        setSize(650,400);
        setResizable(false);
        setTitle("Administrador - Sesión de Id usuario"+ user);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), 
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        try{
            Connection con = conexion.Conectar();
            PreparedStatement pst = con.prepareStatement(
            "select Nombres from empleado where Id_Empleado = '" + user +"'");
            
            ResultSet res=pst.executeQuery();
            if (res.next()) {
                nombre_usuario=res.getString("nombres");
                jLabel_usuario.setText(nombre_usuario);
            } else {
                
            }
        }
        catch(Exception e){
            
            System.err.println("erro en la interfaz administrador");
        }
        
   
        
    }
    
    @Override
    public Image getIconImage(){
    Image retValue =Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
    return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Footer = new javax.swing.JLabel();
        jButton1_gestionar = new javax.swing.JButton();
        jButton_empleados = new javax.swing.JButton();
        jButton_agregarusuario = new javax.swing.JButton();
        jLabel_usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Footer.setText("@ Licencias Creative Commons ");
        getContentPane().add(jLabel_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 210, -1));

        jButton1_gestionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        jButton1_gestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_gestionarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_gestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 120, 100));

        jButton_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capturista.png"))); // NOI18N
        jButton_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_empleadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 120, 100));

        jButton_agregarusuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\baironMartin\\Documents\\MEGA\\unad\\2021-16-1\\PROGRAMACION ORIENTADA A OBJETOS\\Mi Trasporte S.A\\src\\images\\add.png")); // NOI18N
        jButton_agregarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_agregarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, 100));

        jLabel_usuario.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel_usuario.setText("jLabel1");
        getContentPane().add(jLabel_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Empleado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 120, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 120, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agregar usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 120, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_agregarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarusuarioActionPerformed
        // TODO add your handling code here:
        RegistroUsuarios registrar_usuarios = new RegistroUsuarios ();
        registrar_usuarios.setVisible(true);
        
    }//GEN-LAST:event_jButton_agregarusuarioActionPerformed

    private void jButton1_gestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_gestionarActionPerformed
        gestionar_usuarios gestion = new gestionar_usuarios();
        gestion.setVisible(true);
        
    }//GEN-LAST:event_jButton1_gestionarActionPerformed

    private void jButton_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_empleadosActionPerformed
        // TODO add your handling code here:
       Empleado empleado = new Empleado();
        empleado.setVisible(true);
    }//GEN-LAST:event_jButton_empleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_gestionar;
    private javax.swing.JButton jButton_agregarusuario;
    private javax.swing.JButton jButton_empleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Footer;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_usuario;
    // End of variables declaration//GEN-END:variables
}
