/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.conexion;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import static ventanas.gestionar_usuarios.user_update;

/**
 *
 * @author baironMartin
 */
public class gestionar_cliente extends javax.swing.JFrame {
    String user;
    public static String clienteupdate="";
    DefaultTableModel model= new DefaultTableModel();

    /**
     * Creates new form gestionar_cliente
     */
    public gestionar_cliente() {
        initComponents();
        user = Login.user;
        setSize(630,330);
        setResizable(false);
        setTitle("Gestionar usuario - Sesión de Id usuario" + user);        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), 
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
         jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
         try{
            Connection cn= conexion.Conectar();
            PreparedStatement pst = cn.prepareStatement(
                   "select Id_Cliente,Nombres,Apellidos,Telefono,Ciudad from Cliente" );
            
          ResultSet rs =pst.executeQuery();
          jTable_usuarios= new JTable(model);
          jScrollPane1.setViewportView(jTable_usuarios);
          
          model.addColumn("Id_Cliente");
          model.addColumn("Nombres");
          model.addColumn("Apellidos");
          model.addColumn("Telefono");
          model.addColumn("Ciudad");
          
            while (rs.next()) {
                Object []fila = new Object[5];
                
                for (int i = 0; i < 5; i++) {
                   fila[i]=rs.getObject(i + 1);
                    
                }
                model.addRow(fila);
                
            }
            cn.close();
         
        }
        catch(SQLException e){
            
            System.err.println("Error al llenjar la tabla"+e);
              JOptionPane.showMessageDialog(null, "¡¡ERROR !!, contacte al administrador.");
        }
        
        jTable_usuarios.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
              
               int fila_point =jTable_usuarios.rowAtPoint(e.getPoint());
               int columna_point = 0;
               
                if (fila_point > -1) {
                    clienteupdate=(String)model.getValueAt(fila_point, columna_point);
                    informacion_cliente informacion_cliente= new informacion_cliente();
                    informacion_cliente.setVisible(true);
                    
                } else {
                }
                
            }
            
            
            
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Footer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_usuarios = new javax.swing.JTable();
        jLabel_TITULO = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Footer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Footer.setText("@ Licencias Creative Commons ");
        getContentPane().add(jLabel_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 210, -1));

        jTable_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_usuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 590, 150));

        jLabel_TITULO.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel_TITULO.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TITULO.setText("CLIENTES REGISTRADOS");
        getContentPane().add(jLabel_TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionar_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Footer;
    private javax.swing.JLabel jLabel_TITULO;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_usuarios;
    // End of variables declaration//GEN-END:variables
}
