/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.conexion;
import clases.empleados;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.JTextField;

/**
 *
 * @author baironMartin
 */
public class Informacion_usuario extends javax.swing.JFrame {

  String user="",user_update="";
  int Id;
  String id;
  java.sql.Date fecha1;
  String nombre ,apellido,telefono,rol="";
    
    /**
     * Creates new form Informacion_usuario
     */
    public Informacion_usuario() {
        initComponents();
        
        user=Login.user;
        user_update=gestionar_usuarios.user_update;
        
        setSize(650,450);
        setResizable(false);
        setTitle("Información del Usuario - Sesión de Id usuario "+user);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), 
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
         jLabel1_titulo.setText("Informacion del Usuario con Id "+ user_update);
         
         try {
            Connection cn = conexion.Conectar();
             PreparedStatement pst = cn.prepareStatement(
                "select * from  empleado where Id_Empleado ='" + user_update +"'");
             ResultSet rs = pst.executeQuery();
             if (rs.next()){
                 Id=rs.getInt("Id_Empleado");
                 
                 jText_ID.setText(rs.getString("Id_Empleado"));
                 jText_Nombre.setText(rs.getString("Nombres"));
                 jText_apellido.setText(rs.getString("Apellido"));
                 jText_telefono.setText(rs.getString("Telefono"));
                 jComboBox_Rol.setSelectedItem(rs.getString("rol"));
                 fecha.setDate(rs.getDate("F_Nacimiento"));
                 
                 
                 
             } 
             cn.close();
               
             
        } catch (Exception e) {
              System.err.println("Error al cargar usuario "+e);
              JOptionPane.showMessageDialog(null, "¡¡ERROR !!, contacte al administrador.");
        }
         
         
         
    }
     @Override
    public Image getIconImage(){
    Image retValue =Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
    return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_titulo = new javax.swing.JLabel();
        jText_ID = new javax.swing.JTextField();
        jLabel_id1 = new javax.swing.JLabel();
        jLabel_Nombres = new javax.swing.JLabel();
        jText_Nombre = new javax.swing.JTextField();
        jLabel_Apellidos = new javax.swing.JLabel();
        jText_apellido = new javax.swing.JTextField();
        jLabel_FechaNac1 = new javax.swing.JLabel();
        jComboBox_Rol = new javax.swing.JComboBox<>();
        jLabel_Rol = new javax.swing.JLabel();
        jText_telefono = new javax.swing.JTextField();
        jLabel_Telefono = new javax.swing.JLabel();
        jButton_actualizarclave = new javax.swing.JButton();
        jButton_actualizar1 = new javax.swing.JButton();
        jLabel_Footer = new javax.swing.JLabel();
        jButton_borrar = new javax.swing.JButton();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_titulo.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel1_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_titulo.setText("Información del usuario");
        getContentPane().add(jLabel1_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 650, 30));

        jText_ID.setEnabled(false);
        getContentPane().add(jText_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 200, 30));

        jLabel_id1.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_id1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_id1.setText("ID. Empleado");
        getContentPane().add(jLabel_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 200, -1));

        jLabel_Nombres.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Nombres.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombres.setText("Nombre");
        getContentPane().add(jLabel_Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 200, -1));
        getContentPane().add(jText_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 200, 30));

        jLabel_Apellidos.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Apellidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Apellidos.setText("Apellido");
        getContentPane().add(jLabel_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 200, -1));
        getContentPane().add(jText_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, 30));

        jLabel_FechaNac1.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_FechaNac1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FechaNac1.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel_FechaNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 200, -1));

        jComboBox_Rol.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jComboBox_Rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Conductor", "Cajera", "Bodeguero", "Mensajero" }));
        jComboBox_Rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_RolActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 200, 30));

        jLabel_Rol.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Rol.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Rol.setText("Rol");
        getContentPane().add(jLabel_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 200, -1));

        jText_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(jText_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 200, 30));

        jLabel_Telefono.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Telefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Telefono.setText("Telefono");
        getContentPane().add(jLabel_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 200, -1));

        jButton_actualizarclave.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton_actualizarclave.setForeground(new java.awt.Color(51, 51, 51));
        jButton_actualizarclave.setText("Restaurar contraseña");
        jButton_actualizarclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarclaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_actualizarclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 200, -1));

        jButton_actualizar1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton_actualizar1.setForeground(new java.awt.Color(51, 51, 51));
        jButton_actualizar1.setText("Actualizar");
        jButton_actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_actualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 200, -1));

        jLabel_Footer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Footer.setText("@ Licencias Creative Commons ");
        getContentPane().add(jLabel_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 210, -1));

        jButton_borrar.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton_borrar.setForeground(new java.awt.Color(51, 51, 51));
        jButton_borrar.setText("Borrar Usuario");
        jButton_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 200, -1));

        fecha.setBackground(new java.awt.Color(0, 153, 255));
        fecha.setDateFormatString("yyyy/MM/dd");
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 200, 30));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_RolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_RolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_RolActionPerformed

    private void jText_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_telefonoActionPerformed

    private void jButton_actualizarclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarclaveActionPerformed
        RestaurarPassword restaurar = new RestaurarPassword();
        restaurar.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_actualizarclaveActionPerformed

    private void jButton_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_borrarActionPerformed
        // TODO add your handling code here:
        
      
      id= jText_ID.getText().trim();
       int respuesta = JOptionPane.showConfirmDialog(null, "desea eliminar id "+ id);
       
       if(respuesta==0){
            
            try { 
                     
           Borrar_Empleado();
                        
            JOptionPane.showMessageDialog(null, "¡¡Eliminacion Correcta!!");
                         this.dispose();
                       
                         
            }
                     
                  catch (SQLException e) {
                      System.err.println("Error al Eliminar usuario." + e);
                        JOptionPane.showMessageDialog(null, "¡¡ERROR al Eliminar!!, contacte al administrador.");
                 }
           
       }
       
       
      
      
     
    }//GEN-LAST:event_jButton_borrarActionPerformed

    private void jButton_actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizar1ActionPerformed
      // TODO add your handling code here:
      
      int permisos_cmb, validacion=0;
      
      
      Date date =fecha.getDate();
       long d =date.getTime();
       java.sql.Date fecha = new java.sql.Date(d);
      id= jText_ID.getText().trim();
      nombre= jText_Nombre.getText().trim();
      apellido= jText_apellido.getText().trim();
      telefono= jText_telefono.getText().trim();
      
      permisos_cmb=jComboBox_Rol.getSelectedIndex()+1;
      
      fecha1= fecha;
             if (id.equals("")) {
                 jText_ID.setBackground(Color.red);
                 validacion++;
               
             }
             if (nombre.equals("")) {
                 jText_Nombre.setBackground(Color.red);
                 validacion++;
             
             }
             if (apellido.equals("")) {
                 jText_apellido.setBackground(Color.red);
                 validacion++;
                           
             }
             
                           
             
             if (telefono.equals("")) {
                 jText_telefono.setBackground(Color.red);
                 validacion++;
                           
             }
             if (validacion==0){
        
        switch (permisos_cmb) {
            case 1:
                rol="Administrador";
                break;
            case 2:
                rol="Conductor";
                break;
            case 3:
                rol="Cajera";
                break;
            case 4:
                rol="Bodeguero";
                break;
            case 5:
                rol="Mensajero";
                break;
            default:
                break;
            }
                 try { 
                     
                     
             Connection cn = conexion.Conectar();
            PreparedStatement pst1 = cn.prepareStatement(
                "select Id_Empleado FROM empleado where Id_Empleado= '"+ id +"' and not Id_Empleado= '"+ Id +"'");
            ResultSet rs1 = pst1.executeQuery();
            
            if (rs1.next()) {
                jText_ID.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible.");
                cn.close();
            } else{
                Modificar_Empleado();
            
                 
                        JOptionPane.showMessageDialog(null, "¡¡Actualizacion Correcta!!");
                         this.dispose();
            }
                     
                 } catch (SQLException e) {
                      System.err.println("Error al Actualizar usuario." + e);
                        JOptionPane.showMessageDialog(null, "¡¡ERROR al registrar!!, contacte al administrador.");
                 }
                 
         }
             else{
                  JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
             }
      
      
    }//GEN-LAST:event_jButton_actualizar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton_actualizar1;
    private javax.swing.JButton jButton_actualizarclave;
    private javax.swing.JButton jButton_borrar;
    private javax.swing.JComboBox<String> jComboBox_Rol;
    private javax.swing.JLabel jLabel1_titulo;
    private javax.swing.JLabel jLabel_Apellidos;
    private javax.swing.JLabel jLabel_FechaNac1;
    private javax.swing.JLabel jLabel_Footer;
    private javax.swing.JLabel jLabel_Nombres;
    private javax.swing.JLabel jLabel_Rol;
    private javax.swing.JLabel jLabel_Telefono;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_id1;
    private javax.swing.JTextField jText_ID;
    private javax.swing.JTextField jText_Nombre;
    private javax.swing.JTextField jText_apellido;
    private javax.swing.JTextField jText_telefono;
    // End of variables declaration//GEN-END:variables

    void Borrar_Empleado() throws SQLException{
     empleados empleado = new empleados(id,null,null,null,null,null,null);
     empleado.Borrar_Empleado();
    }
    
    void Modificar_Empleado() throws SQLException{
     empleados empleado1 = new empleados(id,nombre,apellido,fecha1,telefono,null,rol);
     empleado1.Modificar_Empleado();
    }
    
     
}

