/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.conexion;
import java.sql.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import  clases.personas;
import clases.empleado;
import java.awt.Color;



/**
 *
 * @author baironMartin
 */
public class Registrar_usuario extends javax.swing.JFrame {

    /**
     * Creates new form Registrar_usuario
     */
    String user;
            
    public Registrar_usuario() {
        user= Login.user;
        initComponents();
          initComponents();
         setSize(650,380);
        setResizable(false);
        setTitle("Registrar Empleado _ secion id usuario "+ user);
        setLocationRelativeTo(null);
         setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), 
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    }
    @Override
    public Image getIconImage(){
    Image retValue =Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
    return retValue;
    }
   
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSDate_fecha = new rojeru_san.componentes.RSDateChooser();
        jComboBox_Rol = new javax.swing.JComboBox<>();
        jPassword_contraseña = new javax.swing.JPasswordField();
        jButton_agregar = new javax.swing.JButton();
        jText_Nombre = new javax.swing.JTextField();
        jText_apellido = new javax.swing.JTextField();
        jText_telefono = new javax.swing.JTextField();
        jLabel_id = new javax.swing.JLabel();
        jLabel_Apellidos = new javax.swing.JLabel();
        jLabel_Nombres = new javax.swing.JLabel();
        jLabel_Rol = new javax.swing.JLabel();
        jLabel_Telefono = new javax.swing.JLabel();
        jLabel_Contraseña = new javax.swing.JLabel();
        jLabel_FechaNac1 = new javax.swing.JLabel();
        jLabel_Footer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(rSDate_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 200, 30));

        jComboBox_Rol.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jComboBox_Rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Conductor", "Cajera", "Bodeguero", "Mensajero" }));
        jComboBox_Rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_RolActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 200, 30));

        jPassword_contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jPassword_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 200, 30));
        jPassword_contraseña.getAccessibleContext().setAccessibleName("");

        jButton_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 160, 100));

        jText_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jText_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 200, 30));

        jText_apellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jText_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, 30));
        jText_apellido.getAccessibleContext().setAccessibleName("");

        jText_telefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jText_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(jText_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 200, 30));

        jLabel_id.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_id.setText("ID. Empleado");
        getContentPane().add(jLabel_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 200, -1));

        jLabel_Apellidos.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Apellidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Apellidos.setText("Apellido");
        getContentPane().add(jLabel_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 200, -1));

        jLabel_Nombres.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Nombres.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombres.setText("Nombre");
        getContentPane().add(jLabel_Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 200, -1));

        jLabel_Rol.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Rol.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Rol.setText("Rol");
        getContentPane().add(jLabel_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 200, -1));

        jLabel_Telefono.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Telefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Telefono.setText("Telefono");
        getContentPane().add(jLabel_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 200, -1));

        jLabel_Contraseña.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Contraseña.setText("Contraseña");
        getContentPane().add(jLabel_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 200, -1));

        jLabel_FechaNac1.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_FechaNac1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FechaNac1.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel_FechaNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 200, -1));

        jLabel_Footer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Footer.setText("@ Licencias Creative Commons ");
        getContentPane().add(jLabel_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 210, -1));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de empleados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, 40));
        getContentPane().add(jTextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 200, 30));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_telefonoActionPerformed

    private void jComboBox_RolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_RolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_RolActionPerformed

    private void jButton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarActionPerformed
       
        Agregar();
        
        
        
                                           

        
    }//GEN-LAST:event_jButton_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_agregar;
    private javax.swing.JComboBox<String> jComboBox_Rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Apellidos;
    private javax.swing.JLabel jLabel_Contraseña;
    private javax.swing.JLabel jLabel_FechaNac1;
    private javax.swing.JLabel jLabel_Footer;
    private javax.swing.JLabel jLabel_Nombres;
    private javax.swing.JLabel jLabel_Rol;
    private javax.swing.JLabel jLabel_Telefono;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JPasswordField jPassword_contraseña;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jText_Nombre;
    private javax.swing.JTextField jText_apellido;
    private javax.swing.JTextField jText_telefono;
    private rojeru_san.componentes.RSDateChooser rSDate_fecha;
    // End of variables declaration//GEN-END:variables

    public void Agregar(){
        int permisos_cmb, validacion = 0;
       String  id ,nombre ,apellido ,telefono ,fecha,rol="",clave;
        
        id= jTextID.getText() .trim();
        nombre= jText_Nombre.getText() .trim();
        apellido=jText_apellido.getText() .trim();
        telefono=jText_telefono.getText() .trim();
        fecha=rSDate_fecha.getFormatoFecha() .trim();
        permisos_cmb=jComboBox_Rol.getSelectedIndex()+1;
        clave=jPassword_contraseña.getText() .trim();
         
             if (id.equals("")) {
                 jTextID.setBackground(Color.red);
                 validacion++;
               
             }
             if (nombre.equals("")) {
                 jText_Nombre.setBackground(Color.red);
                 validacion++;
             
             }
             if (apellido.equals("")) {
                 jText_apellido.setBackground(Color.red);
                 validacion++;
                           
             }
             if (clave.equals("")) {
                 jPassword_contraseña.setBackground(Color.red);
                 validacion++;
                           
             }
             if (telefono.equals("")) {
                 jText_telefono.setBackground(Color.red);
                 validacion++;
                           
             }
        
        switch (permisos_cmb) {
            case 1:
                rol="Administrador";
                break;
            case 2:
                rol="Conductor";
                break;
            case 3:
                rol="Cajera";
                break;
            case 4:
                rol="Bodeguero";
                break;
            case 5:
                rol="Mensajero";
                break;
            default:
                break;
        }
        
        try {
            Connection cn = conexion.Conectar();
            PreparedStatement pst = cn.prepareStatement(
                "select Id_Empleado FROM empleado where Id_Empleado= '"+ id +"'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                jTextID.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible.");
                cn.close();
            } else {
                
                cn.close();
                
                if (validacion == 0) {
                    try {
                        
                        Connection cn2 = conexion.Conectar();
                        PreparedStatement pst2 = cn2.prepareStatement(
                            "insert into usuarios values (?,?,?,?,?,?,?,?,?)");
                        
                             pst2.setString(1, id);
                             pst2.setString(2, nombre);
                             pst2.setString(3, apellido);
                             pst2.setString(4, fecha);
                             pst2.setString(5, telefono);
                             pst2.setString(6, clave);
                             pst2.setString(7, rol);
                             
                        
                        pst2.executeUpdate();
                        cn2.close();
                        
                        limpiar();
                        
                        jTextID.setBackground(Color.green);                
                        jText_Nombre.setBackground(Color.green);               
                        jText_apellido.setBackground(Color.green);            
                        jPassword_contraseña.setBackground(Color.green);               
                        jText_telefono.setBackground(Color.green);
                        
                        JOptionPane.showMessageDialog(null, "Registro exitoso.");
                        this.dispose();
                        
                    } catch (SQLException e) {
                        System.err.println("Error en Registrar usuario." + e);
                        JOptionPane.showMessageDialog(null, "¡¡ERROR al registrar!!, contacte al administrador.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
                }
                
            }
            
        } catch (SQLException e) {
            System.err.println("Error en validar nombre de usario." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR al comparar usuario!!, contacte al administrador.");
        }
        
    }
    public void limpiar(){
        
                 jTextID.setText("");                
                 jText_Nombre.setText("");               
                 jText_apellido.setText("");            
                 jPassword_contraseña.setText("");               
                 jText_telefono.setText("");
                
                 
        
    }
    

}
