/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.conexion;
import clases.empleados;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.JTextField;
import java.util.Date;
import java.sql.Connection;


/**
 *
 * @author Ernesto
 */
public class RegistroUsuarios extends javax.swing.JFrame {   
    
    String user;
      int permisos_cmb, validacion = 0;
      String  id ,nombre ,apellido,telefono,rol="",clave;
      java.sql.Date fecha1;
       

    /**
     * Creates new form RegistrarUsuarios
     */
    public RegistroUsuarios() {
        initComponents();        
        user = Login.user;
        
        setTitle("Registrar nuevo usuario - Sesión de Id usuario " + user);
        setSize(650, 380);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    }       
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_FechaNac1 = new javax.swing.JLabel();
        jText_apellido = new javax.swing.JTextField();
        jLabel_Apellidos = new javax.swing.JLabel();
        jText_Nombre = new javax.swing.JTextField();
        jLabel_Nombres = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jLabel_id = new javax.swing.JLabel();
        jLabel_Telefono = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        jLabel_Contraseña = new javax.swing.JLabel();
        jPassword_contraseña = new javax.swing.JPasswordField();
        jButton_agregar = new javax.swing.JButton();
        ComboBox_rol = new javax.swing.JComboBox<>();
        jLabel_Footer = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Permisos de:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel_FechaNac1.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_FechaNac1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FechaNac1.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel_FechaNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 200, -1));

        jText_apellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jText_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 200, 30));

        jLabel_Apellidos.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Apellidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Apellidos.setText("Apellido");
        getContentPane().add(jLabel_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 200, -1));

        jText_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jText_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 200, 30));

        jLabel_Nombres.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Nombres.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombres.setText("Nombre");
        getContentPane().add(jLabel_Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 200, -1));
        getContentPane().add(jTextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 200, 30));

        jLabel_id.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_id.setText("ID. Empleado");
        getContentPane().add(jLabel_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 200, -1));

        jLabel_Telefono.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Telefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Telefono.setText("Telefono");
        getContentPane().add(jLabel_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 200, -1));
        getContentPane().add(jTextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 200, 30));

        jLabel_Contraseña.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Contraseña.setText("Contraseña");
        getContentPane().add(jLabel_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 200, -1));

        jPassword_contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jPassword_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 200, 30));

        jButton_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 160, 100));

        ComboBox_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Conductor", "Cajera", "Bodeguero", "Mensajero" }));
        getContentPane().add(ComboBox_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 200, 30));

        jLabel_Footer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Footer.setText("@ Licencias Creative Commons ");
        getContentPane().add(jLabel_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 210, -1));

        fecha.setBackground(new java.awt.Color(0, 153, 255));
        fecha.setDateFormatString("yyyy/MM/dd");
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 200, 30));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarActionPerformed

      Date date =fecha.getDate();
       long d =date.getTime();
       java.sql.Date fecha = new java.sql.Date(d);
          fecha1=fecha;
       
        
        id= jTextID.getText() .trim();
        nombre= jText_Nombre.getText() .trim();
        apellido=jText_apellido.getText() .trim();
        telefono=jTextTelefono.getText() .trim();
        permisos_cmb=ComboBox_rol.getSelectedIndex()+1;
        clave=jPassword_contraseña.getText() .trim();
        
        
         
        
       
             if (id.equals("")) {
                 jTextID.setBackground(Color.red);
                 validacion++;
               
             }
             if (nombre.equals("")) {
                 jText_Nombre.setBackground(Color.red);
                 validacion++;
             
             }
             if (apellido.equals("")) {
                 jText_apellido.setBackground(Color.red);
                 validacion++;
                           
             }
             if (clave.equals("")) {
                 jPassword_contraseña.setBackground(Color.red);
                 validacion++;
                           
             }
             if (telefono.equals("")) {
                 jTextTelefono.setBackground(Color.red);
                 validacion++;
                           
             }
        
        switch (permisos_cmb) {
            case 1:
                rol="Administrador";
                break;
            case 2:
                rol="Conductor";
                break;
            case 3:
                rol="Cajera";
                break;
            case 4:
                rol="Bodeguero";
                break;
            case 5:
                rol="Mensajero";
                break;
            default:
                break;
        }
        
        
        try {
            Connection cn = conexion.Conectar();
            PreparedStatement pst = cn.prepareStatement(
                "select Id_Empleado FROM empleado where Id_Empleado= '"+ id +"'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                jTextID.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible.");
                cn.close();
            } else {
                
                cn.close();
                
                if (validacion == 0) {
                    try {
                        
                       Insertar_Empleado();
                        
                       
                        
                        jTextID.setBackground(Color.green);                
                        jText_Nombre.setBackground(Color.green);               
                        jText_apellido.setBackground(Color.green);            
                        jPassword_contraseña.setBackground(Color.green);               
                        jTextTelefono.setBackground(Color.green);
                        
                        JOptionPane.showMessageDialog(null, "Registro exitoso.");
                        this.dispose();
                        
                    } catch (SQLException e) {
                        System.err.println("Error en Registrar usuario." + e);
                        JOptionPane.showMessageDialog(null, "¡¡ERROR al registrar!!, contacte al administrador.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
                }
                
            }
            
        } catch (SQLException e) {
            System.err.println("Error en validar nombre de usario." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR al comparar usuario!!, contacte al administrador.");
        }
        

    }//GEN-LAST:event_jButton_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_rol;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton_agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Apellidos;
    private javax.swing.JLabel jLabel_Contraseña;
    private javax.swing.JLabel jLabel_FechaNac1;
    private javax.swing.JLabel jLabel_Footer;
    private javax.swing.JLabel jLabel_Nombres;
    private javax.swing.JLabel jLabel_Telefono;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JPasswordField jPassword_contraseña;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JTextField jText_Nombre;
    private javax.swing.JTextField jText_apellido;
    // End of variables declaration//GEN-END:variables

    public void Limpiar(){
       jTextID.setText("");                
                 jText_Nombre.setText("");               
                 jText_apellido.setText("");            
                 jPassword_contraseña.setText("");               
                 jTextTelefono.setText("");
        ComboBox_rol.setSelectedIndex(0);
    }
    
    void Insertar_Empleado() throws SQLException{
     empleados empleado = new empleados(id,nombre,apellido,fecha1,telefono,clave,rol);
     empleado.Insertar_Empleado();
    }
    
    
}
