/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.conexion;
import clases.cliente;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author baironMartin
 */
public class Registrar_clientes extends javax.swing.JFrame {
        String user;
        String  id ,nombre ,apellido,telefono,direccion, ciudad;
        java.sql.Date fecha1;
        
    /**
     * Creates new form Registrar_clientes
     */
    public Registrar_clientes() {
        initComponents();
        user = Login.user;
         setSize(550,350);
        setResizable(false);
        setTitle("Información del cliente - Sesión de Id usuario" + user);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), 
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jText_ID = new javax.swing.JTextField();
        jLabel_id = new javax.swing.JLabel();
        jLabel_Nombres = new javax.swing.JLabel();
        jText_Nombre = new javax.swing.JTextField();
        jLabel_Apellidos = new javax.swing.JLabel();
        jText_apellido = new javax.swing.JTextField();
        jLabel_FechaNac1 = new javax.swing.JLabel();
        jLabel_Telefono = new javax.swing.JLabel();
        jText_ciudad = new javax.swing.JTextField();
        jLabel_Direccion = new javax.swing.JLabel();
        jLabel_Rol = new javax.swing.JLabel();
        jButton_agregar = new javax.swing.JButton();
        jText_direccion = new javax.swing.JTextField();
        jText_telefono2 = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 40));
        getContentPane().add(jText_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, 30));

        jLabel_id.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_id.setText("ID. Cliente");
        getContentPane().add(jLabel_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 200, 20));

        jLabel_Nombres.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Nombres.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombres.setText("Nombre");
        getContentPane().add(jLabel_Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 200, -1));
        getContentPane().add(jText_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 200, 30));

        jLabel_Apellidos.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Apellidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Apellidos.setText("Apellido");
        getContentPane().add(jLabel_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 200, -1));
        getContentPane().add(jText_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 200, 30));

        jLabel_FechaNac1.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_FechaNac1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FechaNac1.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel_FechaNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 200, -1));

        jLabel_Telefono.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Telefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Telefono.setText("Telefono");
        getContentPane().add(jLabel_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 200, -1));

        jText_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_ciudadActionPerformed(evt);
            }
        });
        getContentPane().add(jText_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 200, 30));

        jLabel_Direccion.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Direccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Direccion.setText("Direccion:");
        getContentPane().add(jLabel_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 200, -1));

        jLabel_Rol.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel_Rol.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Rol.setText("Ciudad:");
        getContentPane().add(jLabel_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 200, -1));

        jButton_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 130, 80));

        jText_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_direccionActionPerformed(evt);
            }
        });
        getContentPane().add(jText_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 200, 30));

        jText_telefono2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_telefono2ActionPerformed(evt);
            }
        });
        getContentPane().add(jText_telefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 200, 30));
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 200, 30));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 560, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_ciudadActionPerformed

    private void jText_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_direccionActionPerformed

    private void jText_telefono2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_telefono2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_telefono2ActionPerformed

    private void jButton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarActionPerformed
        // TODO add your handling code here:
         int validacion = 0;
       
                     
       Date date =fecha.getDate();
       long d =date.getTime();
       java.sql.Date fecha = new java.sql.Date(d);
         
       
        
        id= jText_ID.getText() .trim();
        nombre= jText_Nombre.getText() .trim();
        apellido=jText_apellido.getText() .trim();
        telefono=jText_telefono2.getText() .trim();
        direccion=jText_direccion.getText().trim();
        ciudad=jText_ciudad.getText().trim();
        
        fecha1=fecha;
         
        
       
             if (id.equals("")) {
                 jText_ID.setBackground(Color.red);
                 validacion++;
               
             }
             if (nombre.equals("")) {
                 jText_Nombre.setBackground(Color.red);
                 validacion++;
             
             }
             if (apellido.equals("")) {
                 jText_apellido.setBackground(Color.red);
                 validacion++;                     
             }
             if (telefono.equals("")) {
                 jText_telefono2.setBackground(Color.red);
                 validacion++;                     
             }
             if (direccion.equals("")) {
                 jText_direccion.setBackground(Color.red);
                 validacion++;                     
             }
             if (ciudad.equals("")) {
                 jText_ciudad.setBackground(Color.red);
                 validacion++;                     
             }
             
              try {
            Connection cn = conexion.Conectar();
            PreparedStatement pst = cn.prepareStatement(
                "select Id_Cliente FROM cliente where Id_Cliente= '"+ id +"'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                jText_ID.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible.");
                cn.close();
            } else {
                
                cn.close();
                
                if (validacion == 0) {
                    try {
                        
                        Insertar_Cliente();
                        
                       
                        
                        jText_ID.setBackground(Color.green);                
                        jText_Nombre.setBackground(Color.green);               
                        jText_apellido.setBackground(Color.green);            
                        jText_ciudad.setBackground(Color.green);               
                        jText_direccion.setBackground(Color.green);
                        jText_telefono2.setBackground(Color.green);
                        
                        JOptionPane.showMessageDialog(null, "Registro exitoso.");
                        this.dispose();
                        
                    } catch (SQLException e) {
                        System.err.println("Error en Registrar usuario." + e);
                        JOptionPane.showMessageDialog(null, "¡¡ERROR al registrar!!, contacte al administrador.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
                }
                
            }
            
        } catch (SQLException e) {
            System.err.println("Error en validar nombre de usario." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR al comparar usuario!!, contacte al administrador.");
        }
    }//GEN-LAST:event_jButton_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton_agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Apellidos;
    private javax.swing.JLabel jLabel_Direccion;
    private javax.swing.JLabel jLabel_FechaNac1;
    private javax.swing.JLabel jLabel_Nombres;
    private javax.swing.JLabel jLabel_Rol;
    private javax.swing.JLabel jLabel_Telefono;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JTextField jText_ID;
    private javax.swing.JTextField jText_Nombre;
    private javax.swing.JTextField jText_apellido;
    private javax.swing.JTextField jText_ciudad;
    private javax.swing.JTextField jText_direccion;
    private javax.swing.JTextField jText_telefono2;
    // End of variables declaration//GEN-END:variables

     void Insertar_Cliente() throws SQLException{
         cliente cliente1 = new cliente(id,nombre,apellido,fecha1,telefono,direccion,ciudad);
         cliente1.Insertar_Cliente();
       
   }
}
